const products = [
  {
    id: 1,
    category: "BEDROOM",
    title: "Boho Pink Cotton Bed Lilen",
    price: 250,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350090/Final%20project%20images/Catalog%20page/Background_1_mfaady.png",
  },
  {
    id: 2,
    category: "BED LINEN",
    title: "Sweetness Bed Linen",
    price: 300,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_5_sbwv4v.png",
  },
  {
    id: 3,
    category: "BED LINEN",
    title: "French Cotton Bed Linen",
    price: 229,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_2_dikz1w.png",
  },
  {
    id: 4,
    category: "BED LINEN",
    title: "Grey Cotton Bed Linen",
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_4_fc1iyf.png",
  },
  {
    id: 5,
    category: "BED LINEN",
    title: "Almond Cotton Bed Linen",
    price: 399,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_5_sbwv4v.png",
  },
  {
    id: 6,
    category: "BED LINEN",
    title: "Yellow Cotton Bed Linen",
    price: 359,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_6_yvcirf.png",
  },
  {
    id: 7,
    category: "BED LINEN",
    title: "Boho Creame Cotton Bed Linen",
    price: 559,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_7_gq6vjt.png",
  },
  {
    id: 8,
    category: "Loungwear",
    title: "Wasabi Cotton Pillow Cases",
    price: 290,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350089/Final%20project%20images/Catalog%20page/Background_8_g0lavf.png",
  },
  {
    id: 9,
    category: "Loungwear",
    title: "Light Pink Cotton Bed Lilen",
    price: 180,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_9_vlicfl.png",
  },
  {
    id: 10,
    category: "Loungwear",
    title: "French Grey Cotton Bed Lilen",
    price: 400,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350087/Final%20project%20images/Catalog%20page/Background_10_nip7mq.png",
  },
  {
    id: 11,
    category: "Loungwear",
    title: "Fresh White Cotton Bed Linen",
    price: 289,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_11_sindbj.png",
  },
  {
    id: 12,
    category: "Loungwear",
    title: "Grey Cotton Bed Linen",
    price: 259,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_12_ifarin.png",
  },
  {
    id: 13,
    category: "Loungwear",
    title: "Creame Cotton Bed Linen",
    price: 176,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350090/Final%20project%20images/Catalog%20page/Background_13_x1s7mz.png",
  },
  {
    id: 14,
    category: "Loungwear",
    title: "Almond Cotton Pillow Cases",
    price: 599,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_14_clwmr9.png",
  },
  {
    id: 15,
    category: "Loungwear",
    title: "Romantic Cotton Bed Linen",
    price: 600,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_15_rabu8y.png",
  },
  {
    id: 16,
    category: "Loungwear",
    title: "Light Grey Cotton Bed Linen",
    price: 900,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350090/Final%20project%20images/Catalog%20page/Background_16_ddafbq.png",
  },
  {
    id: 17,
    category: "Loungwear",
    title: "Ocean Collection Bed Linen",
    price: 856,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350088/Final%20project%20images/Catalog%20page/Background_17_k52veu.png",
  },
  {
    id: 18,
    category: "Loungwear",
    title: "Latte Cotton Bed Linen",
    price: 258,
    img: "https://res.cloudinary.com/dolprgiip/image/upload/v1661350086/Final%20project%20images/Catalog%20page/Background_18_ml3obk.png",
  },
];

export default products;
